name: mesocircuit
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<3.9
  - autopep8
  - c-compiler
  - cxx-compiler
  - cmake
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - ipython
  - boost
  - libtool
  - readline
  - mpi4py
  - openmp
  - gsl
  - cython
  - doxygen
  - graphviz  # for dot
  - pkg-config
  - nose
  - h5py
  - pytest
  - meautility
  - matplotlib
  - ipython
  - jupyter
  - pip
  - pip:
      - junitparser
      - git+https://github.com/LFPy/LFPy@v2.2.6
      - git+https://github.com/NeuralEnsemble/parameters
      - git+https://github.com/INM-6/hybridLFPy@nest3
